version: 2

project_name: folio212

before:
  hooks:
    - go mod tidy

builds:
  - binary: folio212
    main: ./main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  draft: false
  prerelease: auto

# Optional: publish a Homebrew formula into a tap repository.
# This matches the pattern used in steamdensity.
#
# Requirements:
# - Create a tap repo (e.g. github.com/<org>/homebrew-tap)
# - Add a GitHub Actions secret: RELEASE_GITHUB_TOKEN (a PAT with repo access to the tap repo)
brews:
  - name: folio212
    repository:
      owner: nezdemkovski
      name: homebrew-tap
      token: "{{ .Env.RELEASE_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/nezdemkovski/folio212
    description: "Trading212 portfolio checker"
    license: MIT

